name: analysis-essentials
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.12.0
  - aiohttp  # needed for uproot http access
  - boost-histogram
  - hep_ml
  - hepstats
  - hepunits
  - hist
  - ipython
  - matplotlib
  - mplhep
  - nb_conda
  - nb_conda_kernels
  - notebook
  - numpy
  - pandas
  - particle
  - pandoc
  - pip
  - requests  # needed for uproot http access
  - scikit-learn
  - scipy
  - uproot >=5.0.0  # 5.0.0 breaks the httpsource argument with open, TODO upgrade (what's the equivalent?) in the "get_truth" function
  - uv
  - vector
  - wget
  - zfit >=0.26.0
  - zfit-physics >=0.7.0
  #  - xgboost
  - pip:
      - git+https://github.com/hsf-training/python-lesson.git
      - formulate
      - starterkit-ci
      - xgboost
